START TRANSACTION;
CREATE TABLE IF NOT EXISTS data (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    country TEXT NOT NULL,
    date TIMESTAMPTZ,
    local_price NUMERIC(23, 16),
    dollar_ex NUMERIC(24, 17),
    dollar_price NUMERIC(17, 16),
    dollar_ppp NUMERIC(24, 17),
    dollar_valuation NUMERIC(21, 18)
);

COMMIT;